### ISSUE TITLE
api.yotpo.com

### ISSUE THREAD

**Issue by p1r473** [soteria-nou/domain-list#8]
This breaks website showing user reviews of products

**Comment by jaka** [comment]
Hello
First question, how much time do you spend on looking at these lists of domains?

This domain was added as some webpages (say webpage A) displayed content from this domain, like a widget. Since this was third-party domain, irrelavant to webpage A, it was added for the same reason I have already wrote: leaking data to third parties.

**Comment by p1r473** [comment]
Hello,
I spend a long time doing this. I spend about 2-3hrs per day browsing the web and reporting blocklists that break sites. This broke the reviews on the Kaspersky page when I went to see reviews.

The following was broken by this domain. With the domain blocklisted, the reviews did not show up.
![image](https://user-images.githubusercontent.com/9235633/78402378-7a100280-75c8-11ea-878f-4c32dd0077e1.png)

If something breaks, I will report it. No problem if you don't want to whitelist it. Just reporting it in case you agree.

I have whitelisted it on my end.

**Comment by jaka** [comment]
I understand now, I'm going to create a branch without reported domains. I don't know when this domain (and others reported by you) were added, but back then web was much different and blacklisting didn't break much. Now, a majority is using few services (for example disqus) and blocking this breaks many sites.

**Comment by p1r473** [comment]
This is still blocked, by the way. Unsure if you meant to whitelist it.
